# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20180218_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('sexo', 'Sexo'), ('hombre', 'Hombre'), ('mujer', 'Mujer')], default='sexo', max_length=120),
        ),
    ]
